name: Run Trading Bot

on:
  schedule:
    # Run every day at 8:30 AM IST (3:00 AM UTC)
    - cron: '0 3 * * 1-5'
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run trading bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        WHATSAPP_NUMBER: ${{ secrets.WHATSAPP_NUMBER }}
      run: |
        python main.py
      timeout-minutes: 480  # Run for 8 hours (market hours)
